#
# GitLab build pipeline
#

variables:
  CD_APP_NAME: the-app
  CD_APP_TAG: "0.0"
  CD_NAMESPACE_BHR: vws-reis-bhr
  CD_HARBOR_REGISTRY: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl
  CD_TAG: latest

stages:
  - building
  - labeling

# CI_* variables are defined in GitLab group settings, see build log for actual values
before_script:
  - echo "Started by ${GITLAB_USER_LOGIN} at $(date +%Y-%m-%d'-'%H-%M-%S)"
  - unset ${HISTFILE} # Disable shell cache for security purposes

after_script:
  - echo "Ended by ${GITLAB_USER_LOGIN} at $(date +%Y-%m-%d'-'%H-%M-%S)"

build test image:
  environment:
    name: "test-cluster"
  only:
    - main
  stage: building
  image:
    name: gcr.io/kaniko-project/executor:v1.3.0-debug # Must run in own image
    entrypoint: [""]
  script:
    - echo "${DOCKER_AUTH_CONFIG}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - cat ./Dockerfile |
      sed "s~node:14~harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/node:14~g"
      > Dockerfile_derived # Adjust FROM to prevent Docker rate limiting; assuming adjusted image to be present in Harbor; ref. sp-demo/housekeeping
    - cat Dockerfile_derived
    - echo "CI_PROJECT_DIR ${CI_PROJECT_DIR}"
    - pwd
    - "echo ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CP_APP_TAG}"
    # Build and push to Harbor
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile ./Dockerfile_derived
      --destination ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CD_APP_TAG}
    #  --cache=true

add production label:
  stage: labeling
  environment:
    name: test-cluster
  only:
    - main
  when: manual
  script:
    # Put sp_production label (id=1) on image in Harbor
    - "CONTENT_HEADER='Content-Type: application/json'"
    - curl -v -u "${CI_REGISTRY_TEST_USERNAME}:${CI_REGISTRY_TEST_PASSWORD}" -H ${CONTENT_HEADER} https://${CD_HARBOR_REGISTRY}/api/repositories/${CD_APP_NAME}/tags/${CD_TAG}/labels -d '{"id":1}'
