# Default configuration for all pipelines
default:
  tags:
    - default

# Define environment variables that will be used throughout the pipeline
variables:
  CD_ENVIRONMENT: production
  CD_NAMESPACE_BHR: vws-reis-bhr
  CD_HARBOR_REGISTRY: harbor.cicd.s15m.nl

# Define which directories should be cached between pipeline runs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - packages/mvoc/data/${CD_ENVIRONMENT}-last-update-timestamp.txt

# Specify the Docker image that will be used to run the pipeline
image: harbor.cicd.s15m.nl/vws-reis/tool-box:1.2

.check-changes-skip-stage: &check-changes-skip-stage
  - if [ "$CHANGES_DETECTED" != "true" ] && [ "$CI_PIPELINE_SOURCE" == "schedule" ]; then
    echo "No changes detected and a scheduled pipeline, skipping stage";
    exit 0;
    fi

.build-image: &build-image
  environment:
    name: 'test-cluster'
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:v1.3.0-debug
    entrypoint: ['']
  script:
    - echo "${DOCKER_AUTH_CONFIG}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - echo "CI_PROJECT_DIR ${CI_PROJECT_DIR}"
    - pwd
    - 'echo ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CD_APP_TAG}'
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile /packages/${CD_APP_FOLDER}/Dockerfile
      --build-arg buildid=${CD_APP_TAG}
      --destination ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CD_APP_TAG}

# Define the stages that will be used in the pipeline
stages:
  - check-changes
  - test
  - build
  - package
  - deploy

before_script:
  - echo "Started by ${GITLAB_USER_LOGIN} at $(date +%Y-%m-%d'-'%H-%M-%S)"
  - export CD_APP_TAG=$(date -d "$(echo $CI_PIPELINE_CREATED_AT | sed 's/T/ /; s/Z//')" +%Y%m%d%H%M)
  - echo ${CI_PIPELINE_CREATED_AT}
  - echo ${CD_APP_TAG}
  - echo "CHANGES_DETECTED - $CHANGES_DETECTED"
  - unset ${HISTFILE} # Disable shell cache for security purposes

check changes mvoc:
  stage: check-changes
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  cache:
    key: ${CD_ENVIRONMENT}-last-update-timestamp
    paths:
      - packages/mvoc/data/${CD_ENVIRONMENT}-last-update-timestamp.txt
  script:
    - npm ci
    - NPM_OUTPUT=$(ENVIRONMENT=$CD_ENVIRONMENT npm run mvoc:check-changed-documents)
    - echo "NPM script output:"
    - echo "$NPM_OUTPUT"
    - CHANGES_DETECTED=$(echo "$NPM_OUTPUT" | tail -1)
    - echo "CHANGES_DETECTED=$CHANGES_DETECTED" > ${CD_ENVIRONMENT}-changes-detected.env
    - echo $CHANGES_DETECTED
  artifacts:
    paths:
      - ${CD_ENVIRONMENT}-changes-detected.env
      - packages/mvoc/data/${CD_ENVIRONMENT}-last-update-timestamp.txt
    reports:
      dotenv: ${CD_ENVIRONMENT}-changes-detected.env
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

test mvoc:
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  stage: test
  script:
    - *check-changes-skip-stage
    - npm ci
    - npm run mvoc:test
  only:
    - develop
    - staging
    - main
    - alternative

build mvoc website development:
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  stage: build
  script:
    - *check-changes-skip-stage
    - npm ci
    - npm run mvoc:build:development
    - mkdir -p artifacts/mvoc
    - cp -r packages/mvoc/dist artifacts/mvoc/
  artifacts:
    paths:
      - artifacts/mvoc/dist/
  only:
    - develop

build mvoc website staging:
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  stage: build
  script:
    - *check-changes-skip-stage
    - npm ci
    - npm run mvoc:build:staging
    - mkdir -p artifacts/mvoc
    - cp -r packages/mvoc/dist artifacts/mvoc/
  artifacts:
    paths:
      - artifacts/mvoc/dist/
  only:
    - staging

build mvoc website main:
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  stage: build
  script:
    - *check-changes-skip-stage
    - npm ci
    - npm run mvoc:build:production
    - mkdir -p artifacts/mvoc
    - cp -r packages/mvoc/dist artifacts/mvoc/
  artifacts:
    paths:
      - artifacts/mvoc/dist/
  only:
    - main

build mvoc image:
  <<: *build-image
  variables:
    CD_APP_NAME: mijn-vraag-over-corona-frontend
    CD_APP_FOLDER: mvoc
  before_script:
    - export CD_APP_TAG=$(date -d "$(echo $CI_PIPELINE_CREATED_AT | sed 's/T/ /; s/Z//')" +%Y%m%d%H%M)
    - mkdir -p packages/mvoc
    - cp -r artifacts/mvoc/dist packages/mvoc/
  # dependencies:
  #   - build mvoc
  only:
    - develop
    - main
    - staging

build mvoc cms develop:
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  stage: build
  script:
    - npm ci
    - npm run cms:build:development
    - mkdir -p artifacts/cms
    - cp -r packages/cms/dist artifacts/cms/
  artifacts:
    paths:
      - artifacts/cms/dist/
  only:
    - develop

build mvoc cms staging:
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  stage: build
  script:
    - npm ci
    - npm run cms:build:staging
    - mkdir -p artifacts/cms
    - cp -r packages/cms/dist artifacts/cms/
  artifacts:
    paths:
      - artifacts/cms/dist/
  only:
    - staging

build mvoc cms main:
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  stage: build
  script:
    - npm ci
    - npm run cms:build:main
    - mkdir -p artifacts/cms
    - cp -r packages/cms/dist artifacts/cms/
  artifacts:
    paths:
      - artifacts/cms/dist/
  only:
    - main

build mvoc cms alternative:
  image: harbor.cicd.s15m.nl/docker-hub-proxy/library/node:18-alpine
  stage: build
  script:
    - npm ci
    - npm run cms:build:alternative
    - mkdir -p artifacts/cms
    - cp -r packages/cms/dist artifacts/cms/
  artifacts:
    paths:
      - artifacts/cms/dist/
  only:
    - alternative

build mvoc cms image:
  <<: *build-image
  variables:
    CD_APP_NAME: mijn-vraag-over-corona-cms
    CD_APP_FOLDER: cms
  before_script:
    - export CD_APP_TAG=$(date -d "$(echo $CI_PIPELINE_CREATED_AT | sed 's/T/ /; s/Z//')" +%Y%m%d%H%M)
    - mkdir -p packages/cms
    - cp -r artifacts/cms/dist packages/cms/
  only:
    - develop
    - staging
    - main
    - alternative

deploy mvoc image development:
  variables:
    CD_APP_NAME: mijn-vraag-over-corona-frontend
    CD_PIPELINE_CREATED_AT: $CI_PIPELINE_CREATED_AT
    CD_ENVIRONMENT: development
  stage: deploy
  trigger:
    project: vws/reis/nl-covid19-travel-during-corona-deploy
    forward:
      pipeline_variables: true
  only:
    - develop

deploy mvoc image staging:
  variables:
    CD_PIPELINE_CREATED_AT: $CI_PIPELINE_CREATED_AT
    CD_ENVIRONMENT: staging
  stage: deploy
  trigger:
    project: vws/reis/nl-covid19-travel-during-corona-deploy
    forward:
      pipeline_variables: true
  only:
    - staging

deploy mvoc image production:
  variables:
    CD_PIPELINE_CREATED_AT: $CI_PIPELINE_CREATED_AT
    CD_ENVIRONMENT: production
  stage: deploy
  trigger:
    project: vws/reis/nl-covid19-travel-during-corona-deploy
    forward:
      pipeline_variables: true
  only:
    - main

deploy mvoc image alternative:
  variables:
    CD_PIPELINE_CREATED_AT: $CI_PIPELINE_CREATED_AT
    CD_ENVIRONMENT: alternative
  stage: deploy
  trigger:
    project: vws/reis/nl-covid19-travel-during-corona-deploy
    forward:
      pipeline_variables: true
  only:
    - alternative
