#
# GitLab build pipeline
#

variables:
  CD_APP_NAME: travel-during-corona-website
  CD_NAMESPACE_BHR: vws-reis-bhr
  CD_HARBOR_REGISTRY: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl

.build-image: &build-image
  environment:
    name: 'test-cluster'
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.3.0-debug
    entrypoint: ['']
  script:
    - echo "${DOCKER_AUTH_CONFIG}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - cat ./Dockerfile |
      sed "s~node:14-alpine~harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/node:14-alpine~g"
      > Dockerfile_derived # Adjust FROM to prevent Docker rate limiting; assuming adjusted image to be present in Harbor; ref. sp-demo/housekeeping
    - cat Dockerfile_derived
    - echo "CI_PROJECT_DIR ${CI_PROJECT_DIR}"
    - pwd
    - 'echo ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CD_COMMIT_TAG_ID}'
    # Build and push to Harbor
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile ./Dockerfile_derived
      --destination ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CD_COMMIT_TAG_ID}
      --destination ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CD_TAG}
      # --cache=true

stages:
  - test
  - build
  - deploy

# CI_* variables are defined in GitLab group settings, see build log for actual values
before_script:
  - echo "Started by ${GITLAB_USER_LOGIN} at $(date +%Y-%m-%d'-'%H-%M-%S)"
  - export CD_COMMIT_TAG_ID=$(echo ${CI_COMMIT_TAG} | cut -d'-' -f 2)
  - unset ${HISTFILE} # Disable shell cache for security purposes

after_script:
  - echo "Ended by ${GITLAB_USER_LOGIN} at $(date +%Y-%m-%d'-'%H-%M-%S)"

test:
  image: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/node:14-alpine
  stage: test
  script:
    - yarn
    - echo ${CI_TAG_ID}
    - yarn test

build image latest:
  <<: *build-image
  variables:
    CD_TAG: latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^development/'
      when: always
    - when: never

build image staging:
  <<: *build-image
  variables:
    CD_TAG: staging
  rules:
    - if: '$CI_COMMIT_TAG =~ /^staging/'
      when: always
    - when: never

build image production:
  <<: *build-image
  variables:
    CD_TAG: production
  rules:
    - if: '$CI_COMMIT_TAG =~ /^production/'
      when: always
    - when: never

deploy image latest:
  variables:
    CD_APP_TAG: $CD_COMMIT_TAG_ID
    CD_ENVIRONMENT: development
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^development/'
      when: on_success
    - when: never

deploy image staging:
  variables:
    CD_APP_TAG: $CD_COMMIT_TAG_ID
    CD_ENVIRONMENT: staging
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^staging/'
      when: on_success
    - when: never

deploy image production:
  variables:
    CD_APP_TAG: $CD_COMMIT_TAG_ID
    CD_ENVIRONMENT: production
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^production/'
      when: manual
    - when: never
