#
# GitLab build pipeline
#
default:
  tags:
    - default

variables:
  CD_NAMESPACE_BHR: vws-reis-bhr
  CD_HARBOR_REGISTRY: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl

image: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/tool-box:1.2

.build-image: &build-image
  environment:
    name: 'test-cluster'
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.3.0-debug
    entrypoint: ['']
  script:
    - echo "${DOCKER_AUTH_CONFIG}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - cat ./packages/${CD_APP_FOLDER}/Dockerfile |
      sed "s~node:14-alpine~harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/node:14-alpine~g"
      > ./packages/${CD_APP_FOLDER}/Dockerfile_derived
    - cat ./packages/${CD_APP_FOLDER}/Dockerfile_derived
    - echo "CI_PROJECT_DIR ${CI_PROJECT_DIR}"
    - pwd
    - 'echo ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CD_APP_TAG}'
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}
      --dockerfile /packages/${CD_APP_FOLDER}/Dockerfile_derived
      --build-arg buildid=${CD_APP_TAG}
      --destination ${CD_HARBOR_REGISTRY}/vws-reis/${CD_APP_NAME}:${CD_APP_TAG}
      --cache=true

stages:
  - test
  - build
  - label
  - deploy

# CI_* variables are defined in GitLab group settings, see build log for actual values
before_script:
  - echo "Started by ${GITLAB_USER_LOGIN} at $(date +%Y-%m-%d'-'%H-%M-%S)"
  - export CD_APP_TAG=$(echo ${CI_COMMIT_TAG} | cut -d'-' -f 2)
  - echo ${CD_APP_TAG}
  - unset ${HISTFILE} # Disable shell cache for security purposes

after_script:
  - echo "Ended by ${GITLAB_USER_LOGIN} at $(date +%Y-%m-%d'-'%H-%M-%S)"

test common:
  image: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/node:14-alpine
  stage: test
  script:
    - yarn
    - yarn test:common

test reizen:
  image: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/node:14-alpine
  stage: test
  script:
    - yarn
    - yarn test:reizen

test check:
  image: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/node:14-alpine
  stage: test
  script:
    - yarn
    - yarn test:check

# Temporary disbabled to E2E tests (they have never been enabled), because
# it doesn't seem posibible to get the cypress image via the old harbor.
# @TODO: Replace with the below url once new harbor is used for reizen site:
# image: harbor.cicd.s15m.nl/vws-reis-docker-hub/cypress/browsers:node14.16.0-chrome89-ff86
# e2e reizen:
#   image: harbor.diensten.test.overheid.standaardplatform.rijksapps.nl/vws-reis/cypress/browsers:node14.16.0-chrome89-ff86
#   stage: test
#   script:
#     - yarn
#     - yarn e2e:reizen

build reizen image latest:
  <<: *build-image
  variables:
    CD_APP_NAME: travel-during-corona-website
    CD_APP_FOLDER: reizen
  rules:
    - if: '$CI_COMMIT_TAG =~ /^development/'
      when: always
    - when: never

build check image latest:
  <<: *build-image
  variables:
    CD_APP_NAME: quarantaine-check-website
    CD_APP_FOLDER: check
  rules:
    - if: '$CI_COMMIT_TAG =~ /^development/'
      when: always
    - when: never

build reizen image staging:
  <<: *build-image
  variables:
    CD_APP_NAME: travel-during-corona-website
    CD_APP_FOLDER: reizen
  rules:
    - if: '$CI_COMMIT_TAG =~ /^staging/'
      when: always
    - when: never

build check image staging:
  <<: *build-image
  variables:
    CD_APP_NAME: quarantaine-check-website
    CD_APP_FOLDER: check
  rules:
    - if: '$CI_COMMIT_TAG =~ /^staging/'
      when: always
    - when: never

label reizen image production:
  stage: label
  environment:
    name: test-cluster
  variables:
    CD_APP_NAME: travel-during-corona-website
  rules:
    - if: '$CI_COMMIT_TAG =~ /^production/'
      when: always
    - when: never
  script:
    - CD_USERNAME=$(kubectl get secret -n ${CD_NAMESPACE_BHR} sa-user-secret -o jsonpath={.data.username} | base64 --decode)
    - CD_PASSWORD=$(kubectl get secret -n ${CD_NAMESPACE_BHR} sa-user-secret -o jsonpath={.data.password} | base64 --decode)
    - "CONTENT_HEADER='Content-Type:application/json'"
    - curl -v -u "${CD_USERNAME}:${CD_PASSWORD}" -H ${CONTENT_HEADER} https://${CD_HARBOR_REGISTRY}/api/repositories/vws-reis/${CD_APP_NAME}/tags/${CD_APP_TAG}/labels -d '{"id":1}'

label check image production:
  stage: label
  environment:
    name: test-cluster
  variables:
    CD_APP_NAME: quarantaine-check-website
  rules:
    - if: '$CI_COMMIT_TAG =~ /^production/'
      when: always
    - when: never
  script:
    - CD_USERNAME=$(kubectl get secret -n ${CD_NAMESPACE_BHR} sa-user-secret -o jsonpath={.data.username} | base64 --decode)
    - CD_PASSWORD=$(kubectl get secret -n ${CD_NAMESPACE_BHR} sa-user-secret -o jsonpath={.data.password} | base64 --decode)
    - "CONTENT_HEADER='Content-Type:application/json'"
    - curl -v -u "${CD_USERNAME}:${CD_PASSWORD}" -H ${CONTENT_HEADER} https://${CD_HARBOR_REGISTRY}/api/repositories/vws-reis/${CD_APP_NAME}/tags/${CD_APP_TAG}/labels -d '{"id":1}'

deploy reizen image latest:
  variables:
    CD_APP_NAME: travel-during-corona-website
    CD_WEBSITE_COMMIT_TAG: $CI_COMMIT_TAG
    CD_ENVIRONMENT: development
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^development/'
      when: on_success
    - when: never

deploy check image latest:
  variables:
    CD_APP_NAME: quarantaine-check-website
    CD_WEBSITE_COMMIT_TAG: $CI_COMMIT_TAG
    CD_ENVIRONMENT: development
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^development/'
      when: on_success
    - when: never

deploy reizen image staging:
  variables:
    CD_APP_NAME: travel-during-corona-website
    CD_WEBSITE_COMMIT_TAG: $CI_COMMIT_TAG
    CD_ENVIRONMENT: staging
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^staging/'
      when: on_success
    - when: never

deploy check image staging:
  variables:
    CD_APP_NAME: quarantaine-check-website
    CD_WEBSITE_COMMIT_TAG: $CI_COMMIT_TAG
    CD_ENVIRONMENT: staging
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^staging/'
      when: on_success
    - when: never

deploy reizen image production:
  variables:
    CD_APP_NAME: travel-during-corona-website
    CD_WEBSITE_COMMIT_TAG: $CI_COMMIT_TAG
    CD_ENVIRONMENT: production
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^production/'
      when: manual
    - when: never

deploy check image production:
  variables:
    CD_APP_NAME: quarantaine-check-website
    CD_WEBSITE_COMMIT_TAG: $CI_COMMIT_TAG
    CD_ENVIRONMENT: production
  stage: deploy
  trigger: vws/reis/nl-covid19-travel-during-corona-deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^production/'
      when: manual
    - when: never
