// Enum with all available country names
export enum CountrySlugs {
	afghanistan = 'afghanistan',
	albanie = 'albanie',
	algerije = 'algerije',
	andorra = 'andorra',
	angola = 'angola',
	antiguaBarbuda = 'antigua-en-barbuda',
	argentinie = 'argentinie',
	armenie = 'armenie',
	australie = 'australie',
	azerbeidzjan = 'azerbeidzjan',
	bahamas = 'bahamas',
	bahrein = 'bahrein',
	bangladesh = 'bangladesh',
	barbados = 'baarbados',
	belgie = 'belgie',
	belize = 'belize',
	benin = 'benin',
	bhutan = 'bhutan',
	bolivia = 'bolivia',
	bosnieHerzegovina = 'bosnie-herzegovina',
	botswana = 'botswana',
	brazilie = 'brazilie',
	brunei = 'brunei',
	bulgarije = 'bulgarije',
	burkinaFaso = 'burkina-faso',
	burundi = 'burundi',
	cambodja = 'cambodja',
	canada = 'canada',
	centraalAfrikaanseRepubliek = 'centraal-afrikaanse-republiek',
	chili = 'chili',
	china = 'china',
	colombia = 'colombia',
	comoren = 'comoren',
	congoBrazzaville = 'congo-brazzaville',
	congoDemocratischeRepubliek = 'congo-democratische-republiek',
	costaRica = 'costa-rica',
	cuba = 'cuba',
	cyprus = 'cyprus',
	denemarken = 'denemarken',
	djibouti = 'djibouti',
	dominica = 'dominica',
	dominicaanseRepubliek = 'dominicaanse-republiek',
	duitsland = 'duitsland',
	ecuador = 'ecuador',
	egypte = 'egypte',
	elSalvador = 'el-salvador',
	equatoriaalGuinea = 'equatoriaal-guinea',
	eritrea = 'eritrea',
	estland = 'estland',
	ethiopie = 'ethiopie',
	fiji = 'fiji',
	filipijnen = 'filipijnen',
	finland = 'finland',
	frankrijk = 'frankrijk',
	gabon = 'gabon',
	gambia = 'gambia',
	georgie = 'georgie',
	ghana = 'ghana',
	grenada = 'grenada',
	griekenland = 'griekenland',
	guatemala = 'guatemala',
	guinee = 'guinee',
	guineeBissau = 'guinee-bissau',
	guyana = 'guyana',
	haiti = 'haiti',
	honduras = 'honduras',
	hongarije = 'hongarije',
	ierland = 'ierland',
	ijsland = 'ijsland',
	india = 'india',
	indonesie = 'indonesie',
	irak = 'irak',
	iran = 'iran',
	israel = 'israel',
	italie = 'italie',
	ivoorkust = 'ivoorkust',
	jamaica = 'jamaica',
	japan = 'japan',
	jemen = 'jemen',
	jordanie = 'jordanie',
	kaapverdie = 'kaapverdie',
	kameroen = 'kameroen',
	kazachstan = 'kazachstan',
	kenia = 'kenia',
	kirgizie = 'kirgizie',
	kiribati = 'kiribati',
	koeweit = 'koeweit',
	kosovo = 'kosovo',
	kroatie = 'kroatie',
	laos = 'laos',
	lesotho = 'lesotho',
	letland = 'letland',
	libanon = 'libanon',
	liberia = 'liberia',
	libie = 'libie',
	liechtenstein = 'liechtenstein',
	litouwen = 'litouwen',
	luxemburg = 'luxemburg',
	madagaskar = 'madagaskar',
	malawi = 'malawi',
	maldiven = 'maldiven',
	maleisie = 'maleisie',
	mali = 'mali',
	malta = 'malta',
	marokko = 'marokko',
	marshalleilanden = 'marshalleilanden',
	mauritanie = 'mauritanie',
	mauritius = 'mauritius',
	mexico = 'mexico',
	micronesie = 'micronesie',
	moldavie = 'moldavie',
	monaco = 'monaco',
	mongolie = 'mongolie',
	montenegro = 'montenegro',
	mozambique = 'mozambique',
	myanmar = 'myanmar',
	namibie = 'namibie',
	nauru = 'nauru',
	nederland = 'nederland',
	nepal = 'nepal',
	nicaragua = 'nicaragua',
	nieuwZeeland = 'nieuw-zeeland',
	niger = 'niger',
	nigeria = 'nigeria',
	noordKorea = 'noord-korea',
	noordMacedonie = 'noord-macedonie',
	noorwegen = 'noorwegen',
	oeganda = 'oeganda',
	oekraine = 'oekraine',
	oezbekistan = 'oezbekistan',
	oman = 'oman',
	oostenrijk = 'oostenrijk',
	oostTimor = 'oost-timor',
	pakistan = 'pakistan',
	palau = 'palau',
	palestina = 'palestina',
	panama = 'panama',
	papoeaNieuwGuinea = 'papoea-nieuw-guinea',
	paraguay = 'paraguay',
	peru = 'peru',
	polen = 'polen',
	portugal = 'portugal',
	qatar = 'qatar',
	roemenie = 'roemenie',
	rusland = 'rusland',
	rwanda = 'rwanda',
	saintKittsNevis = 'saint-kitts-nevis',
	saintLucia = 'saint-lucia',
	saintVincentGrenadines = 'saint-vincent-en-de-grenadines',
	salomonseilanden = 'salomonseilanden',
	samoa = 'samoa',
	sanMarino = 'san-marino',
	saoTomePrincipe = 'sao-tome-principe',
	saoediArabie = 'saoedi-arabie',
	senegal = 'senegal',
	servie = 'servie',
	seychellen = 'seychellen',
	sierraLeone = 'sierra-leone',
	singapore = 'singapore',
	slovenie = 'slovenie',
	slowakije = 'slowakije',
	soedan = 'soedan',
	somalie = 'somalie',
	spanje = 'spanje',
	sriLanka = 'sri-lanka',
	suriname = 'suriname',
	swaziland = 'swaziland',
	syrie = 'syrie',
	tadzjikistan = 'tadzjikistan',
	taiwan = 'taiwan',
	tanzania = 'tanzania',
	thailand = 'thailand',
	togo = 'togo',
	tonga = 'tonga',
	trinidadTobago = 'trinidad-tobago',
	tsjaad = 'tsjaad',
	tsjechie = 'tsjechie',
	tunesie = 'tunesie',
	turkije = 'turkije',
	turkmenistan = 'turkmenistan',
	tuvalu = 'tuvalu',
	uruguay = 'uruguay',
	vanuatu = 'vanuatu',
	vaticaanstad = 'vaticaanstad',
	venezuela = 'venezuela',
	verenigdKoninkrijk = 'verenigd-koninkrijk',
	verenigdeArabischeEmiraten = 'verenigde-arabische-amiraten',
	verenigdeStaten = 'verenigde-staten',
	vietnam = 'vietnam',
	westelijkeSahara = 'westelijke-sahara',
	witRusland = 'wit-rusland',
	zambia = 'zambia',
	zimbabwe = 'zimbabwe',
	zuidAfrika = 'zuid-afrika',
	zuidKorea = 'zuid-korea',
	zuidSoedan = 'zuid-soedan',
	zweden = 'zweden',
	zwitserland = 'zwitserland',
	aruba = 'aruba',
	bonaire = 'bonaire',
	saba = 'saba',
	stEustacius = 'st-eustacius',
	StMaarten = 'st-maarten',
	curacao = 'curacao',
}

export interface Country {
	fullName: string;
	slug: CountrySlugs;
	coronaMelderCountry: boolean;
	euCountry: boolean;
	schengenCountry: boolean;
	// @TODO:
	// - Remove unknown level, these were group d in old code. Looking at the code I think these
  //    would all default to 'high'.
	// - Validate all levels, I have for example the feeling that group a should be
	//    low risk instead of the high it was.
	riskLevel: 'high' | 'medium' | 'low' | 'unknown';
}

export const countries: Country[] = [
	{
		fullName: 'Afghanistan',
		slug: CountrySlugs.afghanistan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Albanië',
		slug: CountrySlugs.albanie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Algerije',
		slug: CountrySlugs.algerije,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Andorra',
		slug: CountrySlugs.andorra,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Angola',
		slug: CountrySlugs.angola,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Antigua en Barbuda',
		slug: CountrySlugs.antiguaBarbuda,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Argentinië',
		slug: CountrySlugs.argentinie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Armenië',
		slug: CountrySlugs.armenie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Australië',
		slug: CountrySlugs.australie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'low',
	},
	{
		fullName: 'Azerbeidzjan',
		slug: CountrySlugs.azerbeidzjan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: "Bahama's",
		slug: CountrySlugs.bahamas,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Bahrein',
		slug: CountrySlugs.bahrein,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Bangladesh',
		slug: CountrySlugs.bangladesh,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Barbados',
		slug: CountrySlugs.barbados,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'België',
		slug: CountrySlugs.belgie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Belize',
		slug: CountrySlugs.belize,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Benin',
		slug: CountrySlugs.benin,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Bhutan',
		slug: CountrySlugs.bhutan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Bolivia',
		slug: CountrySlugs.bolivia,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Bosnië - Herzegovina',
		slug: CountrySlugs.bosnieHerzegovina,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Botswana',
		slug: CountrySlugs.botswana,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Brazilië',
		slug: CountrySlugs.brazilie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Brunei',
		slug: CountrySlugs.brunei,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Bulgarije',
		slug: CountrySlugs.bulgarije,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Burkina Faso',
		slug: CountrySlugs.burkinaFaso,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Burundi',
		slug: CountrySlugs.burundi,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Cambodja',
		slug: CountrySlugs.cambodja,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Canada',
		slug: CountrySlugs.canada,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Centraal-Afrikaanse Republiek',
		slug: CountrySlugs.centraalAfrikaanseRepubliek,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Chili',
		slug: CountrySlugs.chili,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'China',
		slug: CountrySlugs.china,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'low',
	},
	{
		fullName: 'Colombia',
		slug: CountrySlugs.colombia,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Comoren',
		slug: CountrySlugs.comoren,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Congo-Brazzaville',
		slug: CountrySlugs.congoBrazzaville,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Congo (Democratische Republiek)',
		slug: CountrySlugs.congoDemocratischeRepubliek,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Costa Rica',
		slug: CountrySlugs.costaRica,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Cuba',
		slug: CountrySlugs.cuba,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Cyprus',
		slug: CountrySlugs.cyprus,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Denemarken',
		slug: CountrySlugs.denemarken,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Djibouti',
		slug: CountrySlugs.djibouti,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Dominica',
		slug: CountrySlugs.dominica,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Dominicaanse Republiek',
		slug: CountrySlugs.dominicaanseRepubliek,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Duitsland',
		slug: CountrySlugs.duitsland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Ecuador',
		slug: CountrySlugs.ecuador,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Egypte',
		slug: CountrySlugs.egypte,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'El Salvador',
		slug: CountrySlugs.elSalvador,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Equatoriaal-Guinea',
		slug: CountrySlugs.equatoriaalGuinea,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Eritrea',
		slug: CountrySlugs.eritrea,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Estland',
		slug: CountrySlugs.estland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Ethiopië',
		slug: CountrySlugs.ethiopie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Fiji',
		slug: CountrySlugs.fiji,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Filipijnen',
		slug: CountrySlugs.filipijnen,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Finland',
		slug: CountrySlugs.finland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'medium',
	},
	{
		fullName: 'Frankrijk',
		slug: CountrySlugs.frankrijk,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Gabon',
		slug: CountrySlugs.gabon,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Gambia',
		slug: CountrySlugs.gambia,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Georgië',
		slug: CountrySlugs.georgie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Ghana',
		slug: CountrySlugs.ghana,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Grenada',
		slug: CountrySlugs.grenada,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Griekenland',
		slug: CountrySlugs.griekenland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Guatemala',
		slug: CountrySlugs.guatemala,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Guinee',
		slug: CountrySlugs.guinee,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Guinee-Bissau',
		slug: CountrySlugs.guineeBissau,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Guyana',
		slug: CountrySlugs.guyana,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Haïti',
		slug: CountrySlugs.haiti,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Honduras',
		slug: CountrySlugs.honduras,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Hongarije',
		slug: CountrySlugs.hongarije,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Ierland',
		slug: CountrySlugs.ierland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'IJsland',
		slug: CountrySlugs.ijsland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'medium',
	},
	{
		fullName: 'India',
		slug: CountrySlugs.india,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Indonesië',
		slug: CountrySlugs.indonesie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Irak',
		slug: CountrySlugs.irak,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Iran',
		slug: CountrySlugs.iran,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Israël',
		slug: CountrySlugs.israel,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Italië',
		slug: CountrySlugs.italie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Ivoorkust',
		slug: CountrySlugs.ivoorkust,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Jamaica',
		slug: CountrySlugs.jamaica,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Japan',
		slug: CountrySlugs.japan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'low',
	},
	{
		fullName: 'Jemen',
		slug: CountrySlugs.jemen,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Jordanië',
		slug: CountrySlugs.jordanie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Kaapverdië',
		slug: CountrySlugs.kaapverdie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Kameroen',
		slug: CountrySlugs.kameroen,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Kazachstan',
		slug: CountrySlugs.kazachstan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Kenia',
		slug: CountrySlugs.kenia,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Kirgizië',
		slug: CountrySlugs.kirgizie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Kiribati',
		slug: CountrySlugs.kiribati,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Koeweit',
		slug: CountrySlugs.koeweit,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Kosovo',
		slug: CountrySlugs.kosovo,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Kroatië',
		slug: CountrySlugs.kroatie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Laos',
		slug: CountrySlugs.laos,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Lesotho',
		slug: CountrySlugs.lesotho,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Letland',
		slug: CountrySlugs.letland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Libanon',
		slug: CountrySlugs.libanon,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Liberia',
		slug: CountrySlugs.liberia,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Libië',
		slug: CountrySlugs.libie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Liechtenstein',
		slug: CountrySlugs.liechtenstein,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Litouwen',
		slug: CountrySlugs.litouwen,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Luxemburg',
		slug: CountrySlugs.luxemburg,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Madagaskar',
		slug: CountrySlugs.madagaskar,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Malawi',
		slug: CountrySlugs.malawi,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Maldiven',
		slug: CountrySlugs.maldiven,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Maleisië',
		slug: CountrySlugs.maleisie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Mali',
		slug: CountrySlugs.mali,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Malta',
		slug: CountrySlugs.malta,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Marokko',
		slug: CountrySlugs.marokko,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Marshalleilanden',
		slug: CountrySlugs.marshalleilanden,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Mauritanië',
		slug: CountrySlugs.mauritanie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Mauritius',
		slug: CountrySlugs.mauritius,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Mexico',
		slug: CountrySlugs.mexico,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Micronesië',
		slug: CountrySlugs.micronesie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Moldavië',
		slug: CountrySlugs.moldavie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Monaco',
		slug: CountrySlugs.monaco,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Mongolië',
		slug: CountrySlugs.mongolie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Montenegro',
		slug: CountrySlugs.montenegro,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Mozambique',
		slug: CountrySlugs.mozambique,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Myanmar',
		slug: CountrySlugs.myanmar,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Namibië',
		slug: CountrySlugs.namibie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Nauru',
		slug: CountrySlugs.nauru,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Nederland',
		slug: CountrySlugs.nederland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Nepal',
		slug: CountrySlugs.nepal,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Nicaragua',
		slug: CountrySlugs.nicaragua,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Nieuw-Zeeland',
		slug: CountrySlugs.nieuwZeeland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'low',
	},
	{
		fullName: 'Niger',
		slug: CountrySlugs.niger,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Nigeria',
		slug: CountrySlugs.nigeria,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Noord-Korea',
		slug: CountrySlugs.noordKorea,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Noord-Macedonië',
		slug: CountrySlugs.noordMacedonie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Noorwegen',
		slug: CountrySlugs.noorwegen,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'medium',
	},
	{
		fullName: 'Oeganda',
		slug: CountrySlugs.oeganda,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Oekraïne',
		slug: CountrySlugs.oekraine,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Oezbekistan',
		slug: CountrySlugs.oezbekistan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Oman',
		slug: CountrySlugs.oman,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Oostenrijk',
		slug: CountrySlugs.oostenrijk,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Oost-Timor',
		slug: CountrySlugs.oostTimor,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Pakistan',
		slug: CountrySlugs.pakistan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Palau',
		slug: CountrySlugs.palau,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Palestina',
		slug: CountrySlugs.palestina,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Panama',
		slug: CountrySlugs.panama,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Papoea-Nieuw-Guinea',
		slug: CountrySlugs.papoeaNieuwGuinea,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Paraguay',
		slug: CountrySlugs.paraguay,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Peru',
		slug: CountrySlugs.peru,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Polen',
		slug: CountrySlugs.polen,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Portugal',
		slug: CountrySlugs.portugal,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Qatar',
		slug: CountrySlugs.qatar,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Roemenië',
		slug: CountrySlugs.roemenie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Rusland',
		slug: CountrySlugs.rusland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Rwanda',
		slug: CountrySlugs.rwanda,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'low',
	},
	{
		fullName: 'Saint Kitts en Nevis',
		slug: CountrySlugs.saintKittsNevis,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Saint Lucia',
		slug: CountrySlugs.saintLucia,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Saint Vincent en de Grenadines',
		slug: CountrySlugs.saintVincentGrenadines,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Salomonseilanden',
		slug: CountrySlugs.salomonseilanden,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Samoa',
		slug: CountrySlugs.samoa,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'San Marino',
		slug: CountrySlugs.sanMarino,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Sao Tomé en Principe',
		slug: CountrySlugs.saoTomePrincipe,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Saoedi-Arabië',
		slug: CountrySlugs.saoediArabie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Senegal',
		slug: CountrySlugs.senegal,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Servië',
		slug: CountrySlugs.servie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Seychellen',
		slug: CountrySlugs.seychellen,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Sierra Leone',
		slug: CountrySlugs.sierraLeone,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Singapore',
		slug: CountrySlugs.singapore,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'low',
	},
	{
		fullName: 'Slovenië',
		slug: CountrySlugs.slovenie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Slowakije',
		slug: CountrySlugs.slowakije,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Soedan',
		slug: CountrySlugs.soedan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Somalië',
		slug: CountrySlugs.somalie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Spanje',
		slug: CountrySlugs.spanje,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Sri Lanka',
		slug: CountrySlugs.sriLanka,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Suriname',
		slug: CountrySlugs.suriname,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Swaziland',
		slug: CountrySlugs.swaziland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Syrië',
		slug: CountrySlugs.syrie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Tadzjikistan',
		slug: CountrySlugs.tadzjikistan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Taiwan',
		slug: CountrySlugs.taiwan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Tanzania',
		slug: CountrySlugs.tanzania,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Thailand',
		slug: CountrySlugs.thailand,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'low',
	},
	{
		fullName: 'Togo',
		slug: CountrySlugs.togo,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Tonga',
		slug: CountrySlugs.tonga,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Trinidad en Tobago',
		slug: CountrySlugs.trinidadTobago,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Tsjaad',
		slug: CountrySlugs.tsjaad,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Tsjechië',
		slug: CountrySlugs.tsjechie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Tunesië',
		slug: CountrySlugs.tunesie,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Turkije',
		slug: CountrySlugs.turkije,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Turkmenistan',
		slug: CountrySlugs.turkmenistan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Tuvalu',
		slug: CountrySlugs.tuvalu,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Uruguay',
		slug: CountrySlugs.uruguay,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Vanuatu',
		slug: CountrySlugs.vanuatu,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Vaticaanstad',
		slug: CountrySlugs.vaticaanstad,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Venezuela',
		slug: CountrySlugs.venezuela,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Verenigd Koninkrijk',
		slug: CountrySlugs.verenigdKoninkrijk,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Verenigde Arabische Emiraten',
		slug: CountrySlugs.verenigdeArabischeEmiraten,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Verenigde Staten',
		slug: CountrySlugs.verenigdeStaten,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Vietnam',
		slug: CountrySlugs.vietnam,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Westelijke Sahara',
		slug: CountrySlugs.westelijkeSahara,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Wit-Rusland',
		slug: CountrySlugs.witRusland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Zambia',
		slug: CountrySlugs.zambia,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Zimbabwe',
		slug: CountrySlugs.zimbabwe,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Zuid-Afrika',
		slug: CountrySlugs.zuidAfrika,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Zuid-Korea',
		slug: CountrySlugs.zuidKorea,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'low',
	},
	{
		fullName: 'Zuid-Soedan',
		slug: CountrySlugs.zuidSoedan,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'unknown',
	},
	{
		fullName: 'Zweden',
		slug: CountrySlugs.zweden,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
	{
		fullName: 'Zwitserland',
		slug: CountrySlugs.zwitserland,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},

	// antilles
	{
		fullName: 'Aruba',
		slug: CountrySlugs.aruba,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'medium',
	},
	{
		fullName: 'Bonaire',
		slug: CountrySlugs.bonaire,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'medium',
	},
	{
		fullName: 'Saba',
		slug: CountrySlugs.saba,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'medium',
	},
	{
		fullName: 'St Eustacius',
		slug: CountrySlugs.stEustacius,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'medium',
	},
	{
		fullName: 'St Maarten',
		slug: CountrySlugs.StMaarten,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'medium',
	},
	{
		fullName: 'Curaçao',
		slug: CountrySlugs.curacao,
		coronaMelderCountry: false,
		euCountry: false,
		schengenCountry: false,
		riskLevel: 'high',
	},
];

export const countrySlugs: CountrySlugs[] = countries.map(
	(country) => country.slug,
);
export const countryNames = countries.map((country) => country.fullName);
