import { CountrySlugs, SynonymSlugs } from 'config/countries';

export const countriesNl: { [key in CountrySlugs]: string } = {
	[CountrySlugs.afghanistan]: 'Afghanistan',
	[CountrySlugs.albanie]: 'Albanië',
	[CountrySlugs.algerije]: 'Algerije',
	[CountrySlugs.andorra]: 'Andorra',
	[CountrySlugs.angola]: 'Angola',
	[CountrySlugs.antiguaBarbuda]: 'Antigua en Barbuda',
	[CountrySlugs.argentinie]: 'Argentinië',
	[CountrySlugs.armenie]: 'Armenië',
	[CountrySlugs.australie]: 'Australië',
	[CountrySlugs.azerbeidzjan]: 'Azerbeidzjan',
	[CountrySlugs.bahamas]: "Bahama's",
	[CountrySlugs.bahrein]: 'Bahrein',
	[CountrySlugs.bangladesh]: 'Bangladesh',
	[CountrySlugs.barbados]: 'Barbados',
	[CountrySlugs.belgie]: 'België',
	[CountrySlugs.belize]: 'Belize',
	[CountrySlugs.benin]: 'Benin',
	[CountrySlugs.bhutan]: 'Bhutan',
	[CountrySlugs.bolivia]: 'Bolivia',
	[CountrySlugs.bosnieHerzegovina]: 'Bosnië - Herzegovina',
	[CountrySlugs.botswana]: 'Botswana',
	[CountrySlugs.brazilie]: 'Brazilië',
	[CountrySlugs.brunei]: 'Brunei',
	[CountrySlugs.bulgarije]: 'Bulgarije',
	[CountrySlugs.burkinaFaso]: 'Burkina Faso',
	[CountrySlugs.burundi]: 'Burundi',
	[CountrySlugs.cambodja]: 'Cambodja',
	[CountrySlugs.canada]: 'Canada',
	[CountrySlugs.centraalAfrikaanseRepubliek]: 'Centraal-Afrikaanse Republiek',
	[CountrySlugs.chili]: 'Chili',
	[CountrySlugs.china]: 'China',
	[CountrySlugs.hongKong]: 'Hongkong SAR',
	[CountrySlugs.colombia]: 'Colombia',
	[CountrySlugs.comoren]: 'Comoren',
	[CountrySlugs.congoBrazzaville]: 'Congo-Brazzaville',
	[CountrySlugs.congoDemocratischeRepubliek]: 'Congo (Democratische Republiek)',
	[CountrySlugs.costaRica]: 'Costa Rica',
	[CountrySlugs.cuba]: 'Cuba',
	[CountrySlugs.cyprus]: 'Cyprus',
	[CountrySlugs.denemarken]: 'Denemarken',
	[CountrySlugs.djibouti]: 'Djibouti',
	[CountrySlugs.dominica]: 'Dominica',
	[CountrySlugs.dominicaanseRepubliek]: 'Dominicaanse Republiek',
	[CountrySlugs.duitsland]: 'Duitsland',
	[CountrySlugs.ecuador]: 'Ecuador',
	[CountrySlugs.egypte]: 'Egypte',
	[CountrySlugs.elSalvador]: 'El Salvador',
	[CountrySlugs.equatoriaalGuinea]: 'Equatoriaal-Guinea',
	[CountrySlugs.eritrea]: 'Eritrea',
	[CountrySlugs.estland]: 'Estland',
	[CountrySlugs.ethiopie]: 'Ethiopië',
	[CountrySlugs.fiji]: 'Fiji',
	[CountrySlugs.filipijnen]: 'Filipijnen',
	[CountrySlugs.finland]: 'Finland',
	[CountrySlugs.frankrijk]: 'Frankrijk',
	[CountrySlugs.fransGuyana]: 'Frans-Guyana',
	[CountrySlugs.gabon]: 'Gabon',
	[CountrySlugs.gambia]: 'Gambia',
	[CountrySlugs.georgie]: 'Georgië',
	[CountrySlugs.ghana]: 'Ghana',
	[CountrySlugs.grenada]: 'Grenada',
	[CountrySlugs.griekenland]: 'Griekenland',
	[CountrySlugs.guatemala]: 'Guatemala',
	[CountrySlugs.guinee]: 'Guinee',
	[CountrySlugs.guineeBissau]: 'Guinee-Bissau',
	[CountrySlugs.guyana]: 'Guyana',
	[CountrySlugs.haiti]: 'Haïti',
	[CountrySlugs.honduras]: 'Honduras',
	[CountrySlugs.hongarije]: 'Hongarije',
	[CountrySlugs.ierland]: 'Ierland',
	[CountrySlugs.ijsland]: 'IJsland',
	[CountrySlugs.india]: 'India',
	[CountrySlugs.indonesie]: 'Indonesië',
	[CountrySlugs.irak]: 'Irak',
	[CountrySlugs.iran]: 'Iran',
	[CountrySlugs.israel]: 'Israël',
	[CountrySlugs.italie]: 'Italië',
	[CountrySlugs.ivoorkust]: 'Ivoorkust',
	[CountrySlugs.jamaica]: 'Jamaica',
	[CountrySlugs.japan]: 'Japan',
	[CountrySlugs.jemen]: 'Jemen',
	[CountrySlugs.jordanie]: 'Jordanië',
	[CountrySlugs.kaapverdie]: 'Kaapverdië',
	[CountrySlugs.kameroen]: 'Kameroen',
	[CountrySlugs.kazachstan]: 'Kazachstan',
	[CountrySlugs.kenia]: 'Kenia',
	[CountrySlugs.kirgizie]: 'Kirgizië',
	[CountrySlugs.kiribati]: 'Kiribati',
	[CountrySlugs.koeweit]: 'Koeweit',
	[CountrySlugs.kosovo]: 'Kosovo',
	[CountrySlugs.kroatie]: 'Kroatië',
	[CountrySlugs.laos]: 'Laos',
	[CountrySlugs.lesotho]: 'Lesotho',
	[CountrySlugs.letland]: 'Letland',
	[CountrySlugs.libanon]: 'Libanon',
	[CountrySlugs.liberia]: 'Liberia',
	[CountrySlugs.libie]: 'Libië',
	[CountrySlugs.liechtenstein]: 'Liechtenstein',
	[CountrySlugs.litouwen]: 'Litouwen',
	[CountrySlugs.luxemburg]: 'Luxemburg',
	[CountrySlugs.madagaskar]: 'Madagaskar',
	[CountrySlugs.malawi]: 'Malawi',
	[CountrySlugs.maldiven]: 'Maldiven',
	[CountrySlugs.maleisie]: 'Maleisië',
	[CountrySlugs.mali]: 'Mali',
	[CountrySlugs.malta]: 'Malta',
	[CountrySlugs.marokko]: 'Marokko',
	[CountrySlugs.marshalleilanden]: 'Marshalleilanden',
	[CountrySlugs.mauritanie]: 'Mauritanië',
	[CountrySlugs.mauritius]: 'Mauritius',
	[CountrySlugs.mexico]: 'Mexico',
	[CountrySlugs.micronesia]: 'Micronesia',
	[CountrySlugs.moldavie]: 'Moldavië',
	[CountrySlugs.monaco]: 'Monaco',
	[CountrySlugs.mongolie]: 'Mongolië',
	[CountrySlugs.montenegro]: 'Montenegro',
	[CountrySlugs.mozambique]: 'Mozambique',
	[CountrySlugs.myanmar]: 'Myanmar',
	[CountrySlugs.namibie]: 'Namibië',
	[CountrySlugs.nauru]: 'Nauru',
	[CountrySlugs.nepal]: 'Nepal',
	[CountrySlugs.nicaragua]: 'Nicaragua',
	[CountrySlugs.nieuwZeeland]: 'Nieuw-Zeeland',
	[CountrySlugs.niger]: 'Niger',
	[CountrySlugs.nigeria]: 'Nigeria',
	[CountrySlugs.noordKorea]: 'Noord-Korea',
	[CountrySlugs.noordMacedonie]: 'Noord-Macedonië',
	[CountrySlugs.noorwegen]: 'Noorwegen',
	[CountrySlugs.oeganda]: 'Oeganda',
	[CountrySlugs.oekraine]: 'Oekraïne',
	[CountrySlugs.oezbekistan]: 'Oezbekistan',
	[CountrySlugs.oman]: 'Oman',
	[CountrySlugs.oostenrijk]: 'Oostenrijk',
	[CountrySlugs.oostTimor]: 'Oost-Timor',
	[CountrySlugs.pakistan]: 'Pakistan',
	[CountrySlugs.palau]: 'Palau',
	[CountrySlugs.palestina]: 'Palestina',
	[CountrySlugs.panama]: 'Panama',
	[CountrySlugs.papoeaNieuwGuinea]: 'Papoea-Nieuw-Guinea',
	[CountrySlugs.paraguay]: 'Paraguay',
	[CountrySlugs.peru]: 'Peru',
	[CountrySlugs.polen]: 'Polen',
	[CountrySlugs.portugal]: 'Portugal',
	[CountrySlugs.qatar]: 'Qatar',
	[CountrySlugs.roemenie]: 'Roemenië',
	[CountrySlugs.rusland]: 'Rusland',
	[CountrySlugs.rwanda]: 'Rwanda',
	[CountrySlugs.saintKittsNevis]: 'Saint Kitts en Nevis',
	[CountrySlugs.saintLucia]: 'Saint Lucia',
	[CountrySlugs.saintVincentGrenadines]: 'Saint Vincent en de Grenadines',
	[CountrySlugs.salomonseilanden]: 'Salomonseilanden',
	[CountrySlugs.samoa]: 'Samoa',
	[CountrySlugs.sanMarino]: 'San Marino',
	[CountrySlugs.saoTomePrincipe]: 'Sao Tomé en Principe',
	[CountrySlugs.saoediArabie]: 'Saoedi-Arabië',
	[CountrySlugs.senegal]: 'Senegal',
	[CountrySlugs.servie]: 'Servië',
	[CountrySlugs.seychellen]: 'Seychellen',
	[CountrySlugs.sierraLeone]: 'Sierra Leone',
	[CountrySlugs.singapore]: 'Singapore',
	[CountrySlugs.slovenie]: 'Slovenië',
	[CountrySlugs.slowakije]: 'Slowakije',
	[CountrySlugs.soedan]: 'Soedan',
	[CountrySlugs.somalie]: 'Somalië',
	[CountrySlugs.spanje]: 'Spanje',
	[CountrySlugs.sriLanka]: 'Sri Lanka',
	[CountrySlugs.suriname]: 'Suriname',
	[CountrySlugs.swaziland]: 'Swaziland',
	[CountrySlugs.syrie]: 'Syrië',
	[CountrySlugs.tadzjikistan]: 'Tadzjikistan',
	[CountrySlugs.taiwan]: 'Taiwan',
	[CountrySlugs.tanzania]: 'Tanzania',
	[CountrySlugs.thailand]: 'Thailand',
	[CountrySlugs.togo]: 'Togo',
	[CountrySlugs.tonga]: 'Tonga',
	[CountrySlugs.trinidadTobago]: 'Trinidad en Tobago',
	[CountrySlugs.tsjaad]: 'Tsjaad',
	[CountrySlugs.tsjechie]: 'Tsjechië',
	[CountrySlugs.tunesie]: 'Tunesië',
	[CountrySlugs.turkije]: 'Turkije',
	[CountrySlugs.turkmenistan]: 'Turkmenistan',
	[CountrySlugs.tuvalu]: 'Tuvalu',
	[CountrySlugs.uruguay]: 'Uruguay',
	[CountrySlugs.vanuatu]: 'Vanuatu',
	[CountrySlugs.vaticaanstad]: 'Vaticaanstad',
	[CountrySlugs.venezuela]: 'Venezuela',
	[CountrySlugs.verenigdKoninkrijk]: 'Verenigd Koninkrijk',
	[CountrySlugs.verenigdeArabischeEmiraten]: 'Verenigde Arabische Emiraten',
	[CountrySlugs.verenigdeStatenVanAmerika]: 'Verenigde Staten van Amerika',
	[CountrySlugs.vietnam]: 'Vietnam',
	[CountrySlugs.westelijkeSahara]: 'Westelijke Sahara',
	[CountrySlugs.witRusland]: 'Wit-Rusland',
	[CountrySlugs.zambia]: 'Zambia',
	[CountrySlugs.zimbabwe]: 'Zimbabwe',
	[CountrySlugs.zuidAfrika]: 'Zuid-Afrika',
	[CountrySlugs.zuidKorea]: 'Zuid-Korea',
	[CountrySlugs.zuidSoedan]: 'Zuid-Soedan',
	[CountrySlugs.zweden]: 'Zweden',
	[CountrySlugs.zwitserland]: 'Zwitserland',
	[CountrySlugs.aruba]: 'Aruba',
	[CountrySlugs.bonaire]: 'Bonaire',
	[CountrySlugs.saba]: 'Saba',
	[CountrySlugs.stEustacius]: 'St Eustacius',
	[CountrySlugs.StMaarten]: 'St Maarten',
	[CountrySlugs.curacao]: 'Curaçao',
};

export const synonymsNL: { [key in SynonymSlugs]: string } = {
	[SynonymSlugs.canarischeEilanden]: 'Canarische Eilanden',
	[SynonymSlugs.laPalma]: 'La Palma',
	[SynonymSlugs.tenerife]: 'Tenerife',
	[SynonymSlugs.granCanaria]: 'Gran Canaria',
	[SynonymSlugs.fuerteventura]: 'Fuerteventura',
	[SynonymSlugs.lanzarote]: 'Lanzarote',
	[SynonymSlugs.deBalearen]: 'de Balearen',
	[SynonymSlugs.engeland]: 'Engeland',
	[SynonymSlugs.schotland]: 'Schotland',
	[SynonymSlugs.wales]: 'Wales',
	[SynonymSlugs.noordIerland]: 'Noord-Ierland',
	[SynonymSlugs.dubai]: 'Dubai',
	[SynonymSlugs.abuDhabi]: 'Abu Dhabi',
	[SynonymSlugs.ajman]: 'Ajman',
	[SynonymSlugs.fujairah]: 'Fujairah',
	[SynonymSlugs.sharjah]: 'Sharjah',
	[SynonymSlugs.shariqah]: 'Shariqah',
	[SynonymSlugs.rasAlKhaimah]: 'Ras al-Khaimah',
	[SynonymSlugs.ummAlQaywayn]: 'Umm al-Qaywayn',
	[SynonymSlugs.amerika]: 'Amerika',
};

export const countriesEn: { [key in CountrySlugs]: string } = {
	[CountrySlugs.afghanistan]: 'Afghanistan',
	[CountrySlugs.albanie]: 'Albania',
	[CountrySlugs.algerije]: 'Algeria',
	[CountrySlugs.andorra]: 'Andorra',
	[CountrySlugs.angola]: 'Angola',
	[CountrySlugs.antiguaBarbuda]: 'Antigua and Barbuda',
	[CountrySlugs.argentinie]: 'Argentina',
	[CountrySlugs.armenie]: 'Armenia',
	[CountrySlugs.australie]: 'Australia',
	[CountrySlugs.azerbeidzjan]: 'Azerbaijan',
	[CountrySlugs.bahamas]: 'Bahamas',
	[CountrySlugs.bahrein]: 'Bahrain',
	[CountrySlugs.bangladesh]: 'Bangladesh',
	[CountrySlugs.barbados]: 'Barbados',
	[CountrySlugs.belgie]: 'Belgium',
	[CountrySlugs.belize]: 'Belize',
	[CountrySlugs.benin]: 'Benin',
	[CountrySlugs.bhutan]: 'Bhutan',
	[CountrySlugs.bolivia]: 'Bolivia',
	[CountrySlugs.bosnieHerzegovina]: 'Bosnia and Herzegovina',
	[CountrySlugs.botswana]: 'Botswana',
	[CountrySlugs.brazilie]: 'Brazil',
	[CountrySlugs.brunei]: 'Brunei',
	[CountrySlugs.bulgarije]: 'Bulgaria',
	[CountrySlugs.burkinaFaso]: 'Burkina Faso',
	[CountrySlugs.burundi]: 'Burundi',
	[CountrySlugs.cambodja]: 'Cambodia',
	[CountrySlugs.canada]: 'Canada',
	[CountrySlugs.centraalAfrikaanseRepubliek]: 'Central-African Republic',
	[CountrySlugs.chili]: 'Chili',
	[CountrySlugs.china]: 'China',
	[CountrySlugs.hongKong]: 'Hong Kong SAR',
	[CountrySlugs.colombia]: 'Colombia',
	[CountrySlugs.comoren]: 'Comoros',
	[CountrySlugs.congoBrazzaville]: 'Congo-Brazzaville',
	[CountrySlugs.congoDemocratischeRepubliek]: 'Congo (Democratic Republic)',
	[CountrySlugs.costaRica]: 'Costa Rica',
	[CountrySlugs.cuba]: 'Cuba',
	[CountrySlugs.cyprus]: 'Cyprus',
	[CountrySlugs.denemarken]: 'Denmark',
	[CountrySlugs.djibouti]: 'Djibouti',
	[CountrySlugs.dominica]: 'Dominica',
	[CountrySlugs.dominicaanseRepubliek]: 'Dominican Republic',
	[CountrySlugs.duitsland]: 'Germany',
	[CountrySlugs.ecuador]: 'Ecuador',
	[CountrySlugs.egypte]: 'Egypt',
	[CountrySlugs.elSalvador]: 'El Salvador',
	[CountrySlugs.equatoriaalGuinea]: 'Equatorial Guinea',
	[CountrySlugs.eritrea]: 'Eritrea',
	[CountrySlugs.estland]: 'Estonia',
	[CountrySlugs.ethiopie]: 'Ethiopia',
	[CountrySlugs.fiji]: 'Fiji',
	[CountrySlugs.filipijnen]: 'Philippines',
	[CountrySlugs.finland]: 'Finland',
	[CountrySlugs.frankrijk]: 'France',
	[CountrySlugs.fransGuyana]: 'French Guyana',
	[CountrySlugs.gabon]: 'Gabon',
	[CountrySlugs.gambia]: 'Gambia',
	[CountrySlugs.georgie]: 'Georgia',
	[CountrySlugs.ghana]: 'Ghana',
	[CountrySlugs.grenada]: 'Grenada',
	[CountrySlugs.griekenland]: 'Greece',
	[CountrySlugs.guatemala]: 'Guatemala',
	[CountrySlugs.guinee]: 'Guinea',
	[CountrySlugs.guineeBissau]: 'Guinea-Bissau',
	[CountrySlugs.guyana]: 'Guyana',
	[CountrySlugs.haiti]: 'Haiti',
	[CountrySlugs.honduras]: 'Honduras',
	[CountrySlugs.hongarije]: 'Hongary',
	[CountrySlugs.ierland]: 'Ireland',
	[CountrySlugs.ijsland]: 'Iceland',
	[CountrySlugs.india]: 'India',
	[CountrySlugs.indonesie]: 'Indonesia',
	[CountrySlugs.irak]: 'Iraq',
	[CountrySlugs.iran]: 'Iran',
	[CountrySlugs.israel]: 'Israel',
	[CountrySlugs.italie]: 'Italy',
	[CountrySlugs.ivoorkust]: 'Ivory Coast',
	[CountrySlugs.jamaica]: 'Jamaica',
	[CountrySlugs.japan]: 'Japan',
	[CountrySlugs.jemen]: 'Yemen',
	[CountrySlugs.jordanie]: 'Jordan',
	[CountrySlugs.kaapverdie]: 'Cape Verde',
	[CountrySlugs.kameroen]: 'Cameroon',
	[CountrySlugs.kazachstan]: 'Kazakhstan',
	[CountrySlugs.kenia]: 'Kenya',
	[CountrySlugs.kirgizie]: 'Kyrgyzstan',
	[CountrySlugs.kiribati]: 'Kiribati',
	[CountrySlugs.koeweit]: 'Kuwait',
	[CountrySlugs.kosovo]: 'Kosovo',
	[CountrySlugs.kroatie]: 'Croatia',
	[CountrySlugs.laos]: 'Laos',
	[CountrySlugs.lesotho]: 'Lesotho',
	[CountrySlugs.letland]: 'Latvia',
	[CountrySlugs.libanon]: 'Lebanon',
	[CountrySlugs.liberia]: 'Liberia',
	[CountrySlugs.libie]: 'Libya',
	[CountrySlugs.liechtenstein]: 'Liechtenstein',
	[CountrySlugs.litouwen]: 'Lithuania',
	[CountrySlugs.luxemburg]: 'Luxembourg',
	[CountrySlugs.madagaskar]: 'Madagascar',
	[CountrySlugs.malawi]: 'Malawi',
	[CountrySlugs.maldiven]: 'Maldives',
	[CountrySlugs.maleisie]: 'Malaysia',
	[CountrySlugs.mali]: 'Mali',
	[CountrySlugs.malta]: 'Malta',
	[CountrySlugs.marokko]: 'Marocco',
	[CountrySlugs.marshalleilanden]: 'Marshall Islands',
	[CountrySlugs.mauritanie]: 'Mauritania',
	[CountrySlugs.mauritius]: 'Mauritius',
	[CountrySlugs.mexico]: 'Mexico',
	[CountrySlugs.micronesia]: 'Micronesia',
	[CountrySlugs.moldavie]: 'Moldavia',
	[CountrySlugs.monaco]: 'Monaco',
	[CountrySlugs.mongolie]: 'Mongolia',
	[CountrySlugs.montenegro]: 'Montenegro',
	[CountrySlugs.mozambique]: 'Mozambique',
	[CountrySlugs.myanmar]: 'Myanmar',
	[CountrySlugs.namibie]: 'Namibia',
	[CountrySlugs.nauru]: 'Nauru',
	[CountrySlugs.nepal]: 'Nepal',
	[CountrySlugs.nicaragua]: 'Nicaragua',
	[CountrySlugs.nieuwZeeland]: 'New Zealand',
	[CountrySlugs.niger]: 'Niger',
	[CountrySlugs.nigeria]: 'Nigeria',
	[CountrySlugs.noordKorea]: 'North Korea',
	[CountrySlugs.noordMacedonie]: 'North Macedonia',
	[CountrySlugs.noorwegen]: 'Norway',
	[CountrySlugs.oeganda]: 'Uganda',
	[CountrySlugs.oekraine]: 'Ukraine',
	[CountrySlugs.oezbekistan]: 'Uzbekistan',
	[CountrySlugs.oman]: 'Oman',
	[CountrySlugs.oostenrijk]: 'Austria',
	[CountrySlugs.oostTimor]: 'East Timor',
	[CountrySlugs.pakistan]: 'Pakistan',
	[CountrySlugs.palau]: 'Palau',
	[CountrySlugs.palestina]: 'Palestine',
	[CountrySlugs.panama]: 'Panama',
	[CountrySlugs.papoeaNieuwGuinea]: 'Papua New Guinea',
	[CountrySlugs.paraguay]: 'Paraguay',
	[CountrySlugs.peru]: 'Peru',
	[CountrySlugs.polen]: 'Polend',
	[CountrySlugs.portugal]: 'Portugal',
	[CountrySlugs.qatar]: 'Qatar',
	[CountrySlugs.roemenie]: 'Roemenia',
	[CountrySlugs.rusland]: 'Russia',
	[CountrySlugs.rwanda]: 'Rwanda',
	[CountrySlugs.saintKittsNevis]: 'Saint Kitts and Nevis',
	[CountrySlugs.saintLucia]: 'Saint Lucia',
	[CountrySlugs.saintVincentGrenadines]: 'Saint Vincent and the Grenadines',
	[CountrySlugs.salomonseilanden]: 'Solomon Islands',
	[CountrySlugs.samoa]: 'Samoa',
	[CountrySlugs.sanMarino]: 'San Marino',
	[CountrySlugs.saoTomePrincipe]: 'Sao Tome and Principe',
	[CountrySlugs.saoediArabie]: 'Saudi Arabia',
	[CountrySlugs.senegal]: 'Senegal',
	[CountrySlugs.servie]: 'Serbia',
	[CountrySlugs.seychellen]: 'Seychelles',
	[CountrySlugs.sierraLeone]: 'Sierra Leone',
	[CountrySlugs.singapore]: 'Singapore',
	[CountrySlugs.slovenie]: 'Slovenia',
	[CountrySlugs.slowakije]: 'Slovakia',
	[CountrySlugs.soedan]: 'Sudan',
	[CountrySlugs.somalie]: 'Somalia',
	[CountrySlugs.spanje]: 'Spain',
	[CountrySlugs.sriLanka]: 'Sri Lanka',
	[CountrySlugs.suriname]: 'Suriname',
	[CountrySlugs.swaziland]: 'Swaziland',
	[CountrySlugs.syrie]: 'Syria',
	[CountrySlugs.tadzjikistan]: 'Tajikistan',
	[CountrySlugs.taiwan]: 'Taiwan',
	[CountrySlugs.tanzania]: 'Tanzania',
	[CountrySlugs.thailand]: 'Thailand',
	[CountrySlugs.togo]: 'Togo',
	[CountrySlugs.tonga]: 'Tonga',
	[CountrySlugs.trinidadTobago]: 'Trinidad and Tobago',
	[CountrySlugs.tsjaad]: 'Chad',
	[CountrySlugs.tsjechie]: 'Czech Republic',
	[CountrySlugs.tunesie]: 'Tunesia',
	[CountrySlugs.turkije]: 'Turkey',
	[CountrySlugs.turkmenistan]: 'Turkmenistan',
	[CountrySlugs.tuvalu]: 'Tuvalu',
	[CountrySlugs.uruguay]: 'Uruguay',
	[CountrySlugs.vanuatu]: 'Vanuatu',
	[CountrySlugs.vaticaanstad]: 'Vatican City',
	[CountrySlugs.venezuela]: 'Venezuela',
	[CountrySlugs.verenigdKoninkrijk]: 'United Kingdom',
	[CountrySlugs.verenigdeArabischeEmiraten]: 'United Arab Emirates',
	[CountrySlugs.verenigdeStatenVanAmerika]: 'United States',
	[CountrySlugs.vietnam]: 'Vietnam',
	[CountrySlugs.westelijkeSahara]: 'Western Sahara',
	[CountrySlugs.witRusland]: 'Belarus',
	[CountrySlugs.zambia]: 'Zambia',
	[CountrySlugs.zimbabwe]: 'Zimbabwe',
	[CountrySlugs.zuidAfrika]: 'South Africa',
	[CountrySlugs.zuidKorea]: 'South Korea',
	[CountrySlugs.zuidSoedan]: 'Southern Sudan',
	[CountrySlugs.zweden]: 'Sweden',
	[CountrySlugs.zwitserland]: 'Switzerland',
	[CountrySlugs.aruba]: 'Aruba',
	[CountrySlugs.bonaire]: 'Bonaire',
	[CountrySlugs.saba]: 'Saba',
	[CountrySlugs.stEustacius]: 'St Eustacius',
	[CountrySlugs.StMaarten]: 'Saint Martin',
	[CountrySlugs.curacao]: 'Curaçao',
};

export const synonymsEN: { [key in SynonymSlugs]: string } = {
	[SynonymSlugs.canarischeEilanden]: 'Canary Islands',
	[SynonymSlugs.laPalma]: 'La Palma',
	[SynonymSlugs.tenerife]: 'Tenerife',
	[SynonymSlugs.granCanaria]: 'Gran Canaria',
	[SynonymSlugs.fuerteventura]: 'Fuerteventura',
	[SynonymSlugs.lanzarote]: 'Lanzarote',
	[SynonymSlugs.deBalearen]: 'the Balearic Islands',
	[SynonymSlugs.engeland]: 'England',
	[SynonymSlugs.schotland]: 'Scotland',
	[SynonymSlugs.wales]: 'Wales',
	[SynonymSlugs.noordIerland]: 'Northern Ireland',
	[SynonymSlugs.dubai]: 'Dubai',
	[SynonymSlugs.abuDhabi]: 'Abu Dhabi',
	[SynonymSlugs.ajman]: 'Ajman',
	[SynonymSlugs.fujairah]: 'Fujairah',
	[SynonymSlugs.sharjah]: 'Sharjah',
	[SynonymSlugs.shariqah]: 'Shariqah',
	[SynonymSlugs.rasAlKhaimah]: 'Ras al-Khaimah',
	[SynonymSlugs.ummAlQaywayn]: 'Umm al-Qaywayn',
	[SynonymSlugs.amerika]: 'America',
};
